/**
 * Deluluscan dashboard — Google Workspace SSO + per-person allowlist + email OTP.
 *
 * Three layers, each enforced SERVER-SIDE before any report bytes are sent:
 *
 *   1. SSO       the deployment's access=DOMAIN makes Google demand a target
 *                Workspace login before doGet() runs at all.
 *   2. ALLOWLIST being in the domain is not enough — the signed-in address must
 *                appear in ALLOWED_EMAILS (Script Property), else access is
 *                refused. This is what narrows ~56 staff down to named people.
 *   3. OTP       a one-time code is emailed and must be entered before the
 *                report is served. Verification lasts SESSION_HOURS.
 *
 * FAIL CLOSED is the rule everywhere: if the viewer's identity cannot be
 * determined, access is denied rather than granted. getDashboardHtml() re-checks
 * all three layers, so the report cannot be pulled by calling it directly —
 * the gate page is UI, not the control.
 *
 * Index.html is generated by push.sh and never committed (it carries findings).
 */

// ---- configuration --------------------------------------------------------

/** Fallback allowlist, used only when the ALLOWED_EMAILS Script Property is
 *  unset. To add or remove people WITHOUT a redeploy, edit that property:
 *  Apps Script editor -> Project Settings -> Script Properties
 *      ALLOWED_EMAILS = a@example.com, b@example.com
 *  Run showAllowlist() from the editor to print what is currently in force. */
var DEFAULT_ALLOWED = [
  'rashik.adhikari@example.com',
  'mehdi.karimi@example.com'
];

var OTP_TTL_SECONDS = 600;   // a code is valid for 10 minutes
var MAX_ATTEMPTS = 5;        // wrong guesses before the code is burned
var SESSION_HOURS = 8;       // how long a passed OTP keeps you in

// ---- entry point ----------------------------------------------------------

function doGet() {
  var email = viewerEmail_();

  // Layer 1 — identity. Unknown viewer => refuse. Never assume.
  if (!email) {
    audit_('DENIED — viewer identity unavailable', '(unknown)');
    return denyPage_(
      'We could not confirm which Google account you are signed in as.',
      'Open this link in a browser signed in to your target Google account.');
  }

  // Layer 2 — allowlist.
  if (!isAllowed_(email)) {
    audit_('DENIED — not on the allowlist', email);
    return denyPage_(
      'Your account is not authorised for this report.',
      'Signed in as ' + email + '. Ask the report owner to add you.');
  }

  // Layer 3 — OTP.
  if (isVerified_(email)) {
    audit_('viewed (2FA session active)', email);
    return dashboardPage_();
  }
  audit_('2FA challenge shown', email);
  return gatePage_(email);
}

// ---- identity & allowlist -------------------------------------------------

function viewerEmail_() {
  try {
    return String(Session.getActiveUser().getEmail() || '').toLowerCase().trim();
  } catch (err) {
    return '';   // fail closed
  }
}

function allowlist_() {
  var raw = PropertiesService.getScriptProperties().getProperty('ALLOWED_EMAILS');
  var list = raw ? String(raw).split(',') : DEFAULT_ALLOWED;
  return list
    .map(function (s) { return String(s).toLowerCase().trim(); })
    .filter(function (s) { return s.length > 0; });
}

function isAllowed_(email) {
  return allowlist_().indexOf(email) !== -1;
}

/** Run this from the Apps Script editor to see who currently has access.
 *  Running any function once also triggers the OAuth consent this script needs
 *  (send email + read your address). */
function showAllowlist() {
  var list = allowlist_();
  var src = PropertiesService.getScriptProperties().getProperty('ALLOWED_EMAILS')
    ? 'ALLOWED_EMAILS script property' : 'DEFAULT_ALLOWED in Code.gs';
  console.log('Access allowed for ' + list.length + ' account(s) [' + src + ']:\n  ' +
              list.join('\n  '));
  return list;
}

// ---- OTP ------------------------------------------------------------------

function otpKey_(email) { return 'otp:' + email; }
function attKey_(email) { return 'att:' + email; }
function verKey_(email) { return 'ver:' + email; }

/** Per-viewer state must be keyed by the VIEWER's address explicitly.
 *  UserProperties would be wrong here: the web app runs as the deploying user,
 *  so every viewer would share the deployer's property store. */
function isVerified_(email) {
  var until = PropertiesService.getScriptProperties().getProperty(verKey_(email));
  return !!until && Number(until) > Date.now();
}

function markVerified_(email) {
  PropertiesService.getScriptProperties()
    .setProperty(verKey_(email), String(Date.now() + SESSION_HOURS * 3600 * 1000));
}

function generateOtp_() {
  // Utilities.getUuid() is a v4 UUID (random), unlike Math.random().
  var hex = Utilities.getUuid().replace(/[^0-9a-f]/gi, '').substring(0, 8);
  return ('000000' + (parseInt(hex, 16) % 1000000)).slice(-6);
}

/** Called from the gate page. Emails a fresh code; returns the address it went to. */
function requestOtp() {
  var email = viewerEmail_();
  if (!email || !isAllowed_(email)) throw new Error('Not authorised.');

  var code = generateOtp_();
  var cache = CacheService.getScriptCache();
  cache.put(otpKey_(email), code, OTP_TTL_SECONDS);
  cache.put(attKey_(email), '0', OTP_TTL_SECONDS);

  MailApp.sendEmail({
    to: email,
    subject: 'Deluluscan security report — your one-time code: ' + code,
    body: [
      'Your one-time code for the Deluluscan security dashboard is:',
      '',
      '    ' + code,
      '',
      'It expires in ' + Math.round(OTP_TTL_SECONDS / 60) + ' minutes.',
      '',
      'If you did not just try to open the report, someone signed in to your',
      'the target Google account and reached an access-controlled security report.',
      'Do not share this code. Report it to security@example.com.'
    ].join('\n')
  });

  audit_('OTP emailed', email);
  return email;
}

/** Called from the gate page. Returns true on success, throws with a reason. */
function submitOtp(code) {
  var email = viewerEmail_();
  if (!email || !isAllowed_(email)) throw new Error('Not authorised.');

  var cache = CacheService.getScriptCache();
  var expected = cache.get(otpKey_(email));
  if (!expected) throw new Error('That code has expired. Request a new one.');

  var attempts = Number(cache.get(attKey_(email)) || '0');
  if (attempts >= MAX_ATTEMPTS) {
    cache.remove(otpKey_(email));
    audit_('OTP burned — too many attempts', email);
    throw new Error('Too many incorrect attempts. Request a new code.');
  }
  cache.put(attKey_(email), String(attempts + 1), OTP_TTL_SECONDS);

  if (String(code).trim() !== expected) {
    audit_('OTP incorrect (attempt ' + (attempts + 1) + ')', email);
    throw new Error('Incorrect code. ' + (MAX_ATTEMPTS - attempts - 1) + ' attempt(s) left.');
  }

  cache.remove(otpKey_(email));
  cache.remove(attKey_(email));
  markVerified_(email);
  audit_('2FA passed', email);
  return true;
}

/** The report itself. Re-checks every layer: the gate page is UI, not control. */
function getDashboardHtml() {
  var email = viewerEmail_();
  if (!email || !isAllowed_(email) || !isVerified_(email)) {
    audit_('DENIED — getDashboardHtml without a verified session', email || '(unknown)');
    throw new Error('Not authorised.');
  }
  audit_('report served', email);
  return HtmlService.createHtmlOutputFromFile('Index').getContent();
}

// ---- pages ----------------------------------------------------------------

function dashboardPage_() {
  // createHtmlOutputFromFile does NOT evaluate <?= ?> scriptlets, so the built
  // bundle is served byte-for-byte.
  return HtmlService.createHtmlOutputFromFile('Index')
    .setTitle('Deluluscan — Security Assessment')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

function gatePage_(email) {
  var t = HtmlService.createTemplateFromFile('Gate');
  // Show the FULL signed-in identity, not a masked one. The viewer is already
  // authenticated by Google at this point, so masking hides nothing from an
  // attacker — it only makes a legitimate page look like a phishing page.
  // Reflecting back who Google says you are is the anti-phishing signal.
  t.userEmail = email;
  t.displayName = displayNameFromEmail_(email);
  t.initial = (email.charAt(0) || '?').toUpperCase();
  t.ttlSeconds = OTP_TTL_SECONDS;
  return t.evaluate()
    .setTitle('Deluluscan — verify it’s you')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

/** "rashik.adhikari@example.com" -> "Rashik Adhikari" */
function displayNameFromEmail_(email) {
  var local = String(email).split('@')[0].replace(/[._-]+/g, ' ').trim();
  return local.replace(/\b[a-z]/g, function (c) { return c.toUpperCase(); }) || 'Signed in';
}

/** Inline another project file (used for the brand mark in Gate.html). */
function include(name) {
  return HtmlService.createHtmlOutputFromFile(name).getContent();
}

function denyPage_(headline, detail) {
  var html =
    '<!DOCTYPE html><html><head><base target="_top"><meta name="viewport" ' +
    'content="width=device-width, initial-scale=1"><style>' +
    'body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;' +
    'background:#020617;color:#e2e8f0;font:14px/1.6 ui-sans-serif,system-ui,sans-serif}' +
    '.c{max-width:26rem;padding:2rem;border:1px solid #1e293b;border-radius:12px;' +
    'background:#0f172a;text-align:center}h1{font-size:16px;margin:0 0 .5rem;color:#fca5a5}' +
    'p{margin:.5rem 0;color:#94a3b8;font-size:13px}</style></head><body><div class="c">' +
    '<h1>' + escapeHtml_(headline) + '</h1><p>' + escapeHtml_(detail) + '</p>' +
    '<p style="margin-top:1.25rem;font-size:11px;color:#475569">' +
    'This access attempt has been logged.</p></div></body></html>';
  return HtmlService.createHtmlOutput(html).setTitle('Deluluscan — access denied');
}

// ---- helpers --------------------------------------------------------------

function escapeHtml_(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/** Audit trail — visible under Executions (and Cloud Logging if enabled).
 *  Never throws: a logging failure must not deny a legitimate reader. */
function audit_(what, email) {
  try {
    console.log('[deluluscan-dashboard] ' + what + ' — ' + (email || '(unknown)'));
  } catch (err) { /* ignore */ }
}
