"""Signature database for edge-defence and service fingerprinting.

Data-driven so coverage grows by appending rows, not editing logic:
  - EDGE_SIGS   : WAF / CDN / reverse-proxy vendors (wafw00f/CDN-detector style)
  - BLOCK_MARKERS: body/status tells that a *generic* WAF blocked a probe
  - HONEYPOT_SIGS: known deception-framework banners/markers
  - SERVICE_HINTS: port + banner -> service name (light nmap-style)

Grounded in public research (EnableSecurity/wafw00f header signatures; CDN
vendor header markers CF-Ray/X-Amz-Cf-Id/X-Sucuri-ID/X-Iinfo; honeypot
fingerprinting surveys — Cowrie/Kippo/Dionaea/Glastopf default banners).
Detection only.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class EdgeSig:
    """One WAF/CDN vendor. Each signal is independent; confidence scales with how
    many point at the same vendor (a lone Server header is weak; Server+cf-ray+
    cookie is strong)."""
    name: str
    kind: str                       # waf | cdn | both | proxy
    headers: tuple = ()             # (header_name, value_regex)  value_regex "" = presence
    cookies: tuple = ()             # cookie-name regex (prefix ok)
    server_re: str = ""             # regex against Server header
    body_re: str = ""               # regex against a block/challenge body
    note: str = ""


# name, kind, headers[(h,re)], cookies, server_re, body_re
EDGE_SIGS: list[EdgeSig] = [
    EdgeSig("Cloudflare", "both",
            headers=(("cf-ray", ""), ("cf-cache-status", ""), ("cf-chl-bypass", "")),
            cookies=(r"__cf_bm", r"__cfduid", r"cf_clearance"),
            server_re=r"(?i)cloudflare",
            body_re=r"(?i)Attention Required!|cloudflare|cf-chl|Just a moment\.\.\.",
            note="Cloudflare CDN/WAF (challenge + edge)."),
    EdgeSig("AWS CloudFront", "cdn",
            headers=(("x-amz-cf-id", ""), ("x-amz-cf-pop", ""), ("via", r"(?i)cloudfront")),
            server_re=r"(?i)CloudFront"),
    EdgeSig("AWS WAF", "waf",
            headers=(("x-amzn-requestid", ""), ("x-amzn-waf-action", "")),
            body_re=r"(?i)AWS WAF|Request blocked"),
    EdgeSig("Akamai", "both",
            headers=(("x-akamai-transformed", ""), ("akamai-origin-hop", ""),
                     ("x-akamai-request-id", "")),
            server_re=r"(?i)AkamaiGHost|AkamaiNetStorage",
            body_re=r"(?i)Reference&#32;#\d|akamai"),
    EdgeSig("Fastly", "cdn",
            headers=(("x-served-by", r"(?i)cache-"), ("x-fastly-request-id", ""),
                     ("fastly-restarts", ""), ("via", r"(?i)varnish")),
            note="Fastly (Varnish) edge cache."),
    EdgeSig("Imperva Incapsula", "waf",
            headers=(("x-iinfo", ""), ("x-cdn", r"(?i)incapsula")),
            cookies=(r"visid_incap_", r"incap_ses_", r"nlbi_"),
            body_re=r"(?i)Incapsula incident ID|_Incapsula_Resource"),
    EdgeSig("Sucuri CloudProxy", "waf",
            headers=(("x-sucuri-id", ""), ("x-sucuri-cache", "")),
            server_re=r"(?i)Sucuri/Cloudproxy",
            body_re=r"(?i)Sucuri WebSite Firewall|Access Denied - Sucuri"),
    EdgeSig("F5 BIG-IP ASM", "waf",
            headers=(("x-waf-event-info", ""),),
            cookies=(r"TS[0-9a-f]{6,}", r"BIGipServer", r"F5_"),
            body_re=r"(?i)The requested URL was rejected|support ID is"),
    EdgeSig("Barracuda", "waf",
            cookies=(r"barra_counter_session", r"BNI__BARRACUDA", r"BNES_"),
            body_re=r"(?i)You have been blocked|Barracuda"),
    EdgeSig("Fortinet FortiWeb", "waf",
            cookies=(r"FORTIWAFSID",),
            server_re=r"(?i)FortiWeb",
            body_re=r"(?i)Web Page Blocked|fortinet"),
    EdgeSig("DDoS-Guard", "both", server_re=r"(?i)ddos-guard",
            headers=(("x-ddg-request-id", ""),)),
    EdgeSig("DataDome", "waf",
            headers=(("x-datadome", ""), ("x-dd-b", "")),
            cookies=(r"datadome",),
            body_re=r"(?i)datadome|blocked by the security policy"),
    EdgeSig("Azure Front Door / WAF", "both",
            headers=(("x-azure-ref", ""), ("x-fd-int-roxy-purgeid", ""), ("x-azure-fdid", ""))),
    EdgeSig("ModSecurity", "waf",
            server_re=r"(?i)mod_security|NOYB",
            body_re=r"(?i)Mod_Security|This error was generated by Mod_Security|not acceptable"),
    EdgeSig("Wordfence", "waf",
            body_re=r"(?i)Generated by Wordfence|Your access to this site has been limited"),
    EdgeSig("Varnish Cache", "proxy",
            headers=(("x-varnish", ""), ("via", r"(?i)varnish"))),
    EdgeSig("nginx (reverse proxy)", "proxy", server_re=r"(?i)^nginx"),
    EdgeSig("Envoy", "proxy", server_re=r"(?i)envoy",
            headers=(("x-envoy-upstream-service-time", ""),)),
]

# Generic "a WAF blocked this probe" tells (used on the ACTIVE probe response when
# no specific vendor matched). Status codes that a WAF commonly returns on block.
BLOCK_STATUSES = (403, 406, 419, 429, 501, 999)
BLOCK_BODY_RE = (r"(?i)request (blocked|denied|rejected)", r"(?i)web application firewall",
                 r"(?i)malicious|attack detected|security policy",
                 r"(?i)forbidden by administrative rules", r"(?i)access denied")

# name, kind, matcher(s). Honeypots are inherently uncertain -> tentative.
@dataclass
class HoneypotSig:
    name: str
    where: str                      # banner | header | body | heuristic
    pattern: str = ""
    note: str = ""


HONEYPOT_SIGS: list[HoneypotSig] = [
    HoneypotSig("Cowrie/Kippo SSH", "banner",
                r"SSH-2\.0-OpenSSH_5\.1p1 Debian-5|SSH-2\.0-OpenSSH_6\.0p1 Debian-4\+deb7u2",
                "Default Cowrie/Kippo SSH banner (commonly left unchanged)."),
    HoneypotSig("Glastopf web", "body", r"(?i)glastopf|Blog Comments.*Powered",
                "Glastopf web-app honeypot marker."),
    HoneypotSig("Dionaea", "banner", r"(?i)dionaea", "Dionaea malware honeypot."),
    HoneypotSig("Conpot ICS", "banner", r"(?i)Siemens, SIMATIC|Technodrome",
                "Conpot ICS/SCADA honeypot default identity."),
    HoneypotSig("Honeytrap generic", "header", r"(?i)honeytrap", ""),
    HoneypotSig("HoneyPy / mock", "banner", r"(?i)honeypy|honeyd", ""),
]

# port -> (service, banner_regex_optional). Light service map for banner grabs.
SERVICE_HINTS: dict[int, tuple] = {
    21: ("ftp", r"(?i)^220.*ftp"), 22: ("ssh", r"(?i)^SSH-"),
    23: ("telnet", r""), 25: ("smtp", r"(?i)^220.*smtp|esmtp"),
    53: ("dns", r""), 80: ("http", r"(?i)^HTTP/"),
    110: ("pop3", r"(?i)^\+OK"), 111: ("rpcbind", r""),
    135: ("msrpc", r""), 139: ("netbios-ssn", r""),
    143: ("imap", r"(?i)^\* OK"), 443: ("https", r""),
    445: ("microsoft-ds/smb", r""), 465: ("smtps", r""),
    587: ("smtp-submission", r"(?i)^220"), 993: ("imaps", r""),
    995: ("pop3s", r""), 1433: ("mssql", r""), 1521: ("oracle-tns", r""),
    2049: ("nfs", r""), 2375: ("docker-api (unencrypted!)", r""),
    2376: ("docker-api-tls", r""), 3000: ("http-alt/grafana", r"(?i)grafana|^HTTP/"),
    3306: ("mysql", r"(?i)mysql|mariadb"), 3389: ("rdp", r""),
    5432: ("postgresql", r""), 5601: ("kibana", r"(?i)kibana|^HTTP/"),
    5900: ("vnc", r"(?i)^RFB"), 5984: ("couchdb", r"(?i)couchdb|^HTTP/"),
    6379: ("redis", r"(?i)redis|^-NOAUTH|^\+PONG"), 8080: ("http-proxy/alt", r"(?i)^HTTP/"),
    8443: ("https-alt", r""), 8500: ("consul", r"(?i)consul|^HTTP/"),
    9000: ("sonarqube/php-fpm", r""), 9200: ("elasticsearch", r'(?i)"cluster_name"|lucene|^HTTP/'),
    9300: ("elasticsearch-transport", r""), 11211: ("memcached", r"(?i)STAT |VERSION"),
    15672: ("rabbitmq-mgmt", r"(?i)rabbitmq|^HTTP/"), 27017: ("mongodb", r"(?i)mongodb|ismaster"),
    6443: ("kubernetes-api", r"(?i)^HTTP/|kubernetes"),
}

# Ports that should almost never be internet-exposed; presence is a finding.
DANGEROUS_OPEN_PORTS = {
    2375: "Unencrypted Docker API — full container/host takeover if reachable.",
    2376: "Docker API (TLS) — verify client-cert auth is enforced.",
    6379: "Redis — often unauthenticated; RCE via config-rewrite / module load.",
    9200: "Elasticsearch — frequently unauthenticated data/RCE surface.",
    11211: "Memcached — unauthenticated; UDP amplification source.",
    27017: "MongoDB — historically unauthenticated data exposure.",
    5432: "PostgreSQL exposed to the network.",
    3306: "MySQL/MariaDB exposed to the network.",
    1433: "MSSQL exposed to the network.",
    6443: "Kubernetes API server — verify anonymous-auth is disabled.",
    9300: "Elasticsearch transport — cluster join / RCE surface.",
}
